#!/bin/bash -eu
set -o pipefail

log() { echo "[test/db-partial-migrations/assert-final-schema] $*"; }

if ! diff test/db-partial-migrations/expected-schema.sql <(./test/db-partial-migrations/dump-postgres-schema); then
	log "!!!"
	log "!!! Schema differences detected.  See above for details."
	log "!!!"
  exit 1
fi
