#!/bin/bash -eux
set -o pipefail

make base

node ./lib/bin/cli.js user-create  -u x@example.com -p secret1234
node ./lib/bin/cli.js user-promote -u x@example.com

make run &

echo 'Sleeping... (TODO: should wait for backend to be available)'
sleep 10
echo 'Woke up!'

cd benchmarker
npm ci
node index.js -s http://localhost:8383 -P secret1234
