version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19.3
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_PASSWORD: odktest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: node .circleci/initdb.js
      - run: make base
      - run: node ./lib/bin/cli.js user-create -u x@example.com -p secret1234
      - run: cd benchmarker && npm ci && node index.js -s http://localhost:8383 -P secret1234
