version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19.3
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_PASSWORD: odktest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: node .circleci/initdb.js
      - run: make test-full

