version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
      - image: cimg/postgres:9.6
        environment:
          POSTGRES_PASSWORD: odktest

    working_directory: ~/repo

    steps:
      - checkout
      - run: node lib/bin/check-file-headers.js
      - run: npm ci
      - run: node lib/bin/create-docker-databases.js
      - run: make test-full

