blank_issues_enabled: false
contact_links: 
  - name: "Blank issue"
    about: "Create a new issue from scratch in getodk/central"
    url: "https://github.com/getodk/central/issues/new"
  - name: "Report an issue"
    about: "For when Central is behaving in an unexpected way"
    url: "https://forum.getodk.org/c/support/6"
  - name: "Request a feature"
    about: "For when Central is missing functionality"
    url: "https://forum.getodk.org/c/features/9"
  - name: "Everything else"
    about: "For everything else"
    url: "https://forum.getodk.org/c/support/6"
