const { testService } = require('../setup');

describe('authentication', () => {
  const anonymousEndpoints = [
    { method: 'POST', url: '/v1/sessions', skipForOidc: true },
    { method: 'POST', url: '/v1/users/reset/initiate', skipForOidc: true },
  ];

  describe('anonymous endpoints', () => {
    anonymousEndpoints.filter(e => process.env.TEST_AUTH !== 'oidc' || !e.skipForOidc).forEach(({ method, url }) => {
      it(`should not return 401 for ${method} ${url}`, testService(async service => {
        await service[method.toLowerCase()](url)
          .then((res) => {
            res.status.should.not.be.equal(401);
          });
      }));
    });
  });

  /* eslint-disable no-multi-spaces */
  const restrictedEndpoints = [
    { method: 'GET',    url: '/v1/analytics/preview' },
    { method: 'GET',    url: '/v1/assignments' },
    { method: 'GET',    url: '/v1/assignments/role-id' },
    { method: 'DELETE', url: '/v1/assignments/role-id/actor-id' },
    { method: 'POST',   url: '/v1/assignments/role-id/actor-id' },
    { method: 'GET',    url: '/v1/audits' },
    { method: 'POST',   url: '/v1/backup' },
    { method: 'DELETE', url: '/v1/config/some-key' },
    { method: 'GET',    url: '/v1/config/some-key' },
    { method: 'POST',   url: '/v1/config/some-key' },
    { method: 'GET',    url: '/v1/form-links/some-enketo-id/form' },
    { method: 'POST',   url: '/v1/projects' },
    { method: 'GET',    url: '/v1/projects' },
    { method: 'PUT',    url: '/v1/projects/1' },
    { method: 'DELETE', url: '/v1/projects/1' },
    { method: 'PATCH',  url: '/v1/projects/1' },
    { method: 'GET',    url: '/v1/projects/1' },
    { method: 'POST',   url: '/v1/projects/1/app-users' },
    { method: 'GET',    url: '/v1/projects/1/app-users' },
    { method: 'DELETE', url: '/v1/projects/1/app-users/app-user-id' },
    { method: 'GET',    url: '/v1/projects/1/assignments' },
    { method: 'GET',    url: '/v1/projects/1/assignments/forms' },
    { method: 'GET',    url: '/v1/projects/1/assignments/forms/role-id' },
    { method: 'GET',    url: '/v1/projects/1/assignments/role-id' },
    { method: 'DELETE', url: '/v1/projects/1/assignments/role-id/actor-id' },
    { method: 'POST',   url: '/v1/projects/1/assignments/role-id/actor-id' },
    { method: 'POST',   url: '/v1/projects/1/datasets' },
    { method: 'GET',    url: '/v1/projects/1/datasets' },
    { method: 'PATCH',  url: '/v1/projects/1/datasets/tree' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree.svc' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree.svc/$metadata' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree.svc/Entities' },
    { method: 'POST',   url: '/v1/projects/1/datasets/tree/entities' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities.csv' },
    { method: 'PATCH',  url: '/v1/projects/1/datasets/tree/entities/uuid' },
    { method: 'DELETE', url: '/v1/projects/1/datasets/tree/entities/uuid' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities/uuid' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities/uuid/audits' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities/uuid/diffs' },
    { method: 'POST',   url: '/v1/projects/1/datasets/tree/entities/uuid/restore' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/entities/uuid/versions' },
    { method: 'GET',    url: '/v1/projects/1/datasets/tree/integrity', openrosa: true },
    { method: 'POST',   url: '/v1/projects/1/datasets/tree/properties' },
    { method: 'GET',    url: '/v1/projects/1/formList', openrosa: true },
    { method: 'POST',   url: '/v1/projects/1/forms' },
    { method: 'GET',    url: '/v1/projects/1/forms' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple' },
    { method: 'PATCH',  url: '/v1/projects/1/forms/simple' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.svc' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.svc/$metadata' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.svc/Submissions' },
    { method: 'GET',    url: "/v1/projects/1/forms/simple.svc/Submissions('uuid')" },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.svc/child' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.xls' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.xlsx' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/assignments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/assignments/role-id' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/assignments/role-id/actor-id' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/assignments/role-id/actor-id' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/attachments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/dataset-diff' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/draft' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.svc' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.svc/$metadata' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.svc/Submissions' },
    { method: 'GET',    url: "/v1/projects/1/forms/simple/draft.svc/Submissions('uuid')" },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.svc/child' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.xls' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.xlsx' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/attachments' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/draft/attachments/attachment-name' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/attachments/attachment-name' },
    { method: 'PATCH',  url: '/v1/projects/1/forms/simple/draft/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/dataset-diff' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/fields' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/manifest', openrosa: true },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/publish' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/submission', openrosa: true },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submission', openrosa: true },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/submissions' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/submissions.csv' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions.csv' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/submissions.csv.zip' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions.csv.zip' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/keys' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/diffs' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/versions' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/versions/uuid' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/versions/uuid.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/versions/uuid/attachments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/root-uuid/versions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/submitters' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid' },
    { method: 'PUT',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid/attachments' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/draft/submissions/uuid/attachments/attachment-name' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/draft/submissions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/draft/submissions/uuid/audits' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/fields' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/manifest', openrosa: true },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/public-links' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/public-links' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/public-links/public-link-id' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/restore' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions.csv' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions.csv' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions.csv.zip' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions.csv.zip' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/keys' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/diffs' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/versions' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/versions/uuid' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/versions/uuid.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/versions/uuid/attachments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/root-uuid/versions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/submitters' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/submissions/uuid' },
    { method: 'PATCH',  url: '/v1/projects/1/forms/simple/submissions/uuid' },
    { method: 'PUT',    url: '/v1/projects/1/forms/simple/submissions/uuid' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid/attachments' },
    { method: 'DELETE', url: '/v1/projects/1/forms/simple/submissions/uuid/attachments/attachment-name' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid/audits' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions/uuid/comments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid/comments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/submissions/uuid/edit' },
    { method: 'POST',   url: '/v1/projects/1/forms/simple/submissions/uuid/restore' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1.xls' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1.xlsx' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1.xml' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1/attachments' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1/attachments/attachment-name' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1/fields' },
    { method: 'GET',    url: '/v1/projects/1/forms/simple/versions/version-1/manifest', openrosa: true },
    { method: 'POST',   url: '/v1/projects/1/key' },
    { method: 'POST',   url: '/v1/projects/1/submission', openrosa: true },
    { method: 'GET',    url: '/v1/projects/1/submission', openrosa: true },
    { method: 'GET',    url: '/v1/roles' },
    { method: 'GET',    url: '/v1/roles/role-id' },
    { method: 'DELETE', url: '/v1/sessions/current' },
    { method: 'GET',    url: '/v1/sessions/restore' },
    { method: 'DELETE', url: '/v1/sessions/some-token' },
    { method: 'DELETE', url: '/v1/user-preferences/project/1/property-name' },
    { method: 'PUT',    url: '/v1/user-preferences/project/1/property-name' },
    { method: 'DELETE', url: '/v1/user-preferences/site/property-name' },
    { method: 'PUT',    url: '/v1/user-preferences/site/property-name' },
    { method: 'POST',   url: '/v1/users' },
    { method: 'GET',    url: '/v1/users' },
    { method: 'DELETE', url: '/v1/users/1' },
    { method: 'PATCH',  url: '/v1/users/1' },
    { method: 'GET',    url: '/v1/users/1' },
    { method: 'PUT',    url: '/v1/users/1/password', skipForOidc: true },
    { method: 'GET',    url: '/v1/users/current' },
    // This endpoint requires auth only if `invalidate=true` is requested
    { method: 'POST',   url: '/v1/users/reset/initiate?invalidate=true', skipForOidc: true },
    { method: 'POST',   url: '/v1/users/reset/verify', skipForOidc: true }
  ];
  /* eslint-enable no-multi-spaces */

  describe('restricted endpoints', () => {
    restrictedEndpoints.filter(e => process.env.TEST_AUTH !== 'oidc' || !e.skipForOidc).forEach(({ method, url, openrosa }) => {
      it(`should return 401 for the ${method} ${url}`, testService(async service => {
        let request = service[method.toLowerCase()](url);

        if (openrosa) {
          request = request.set('X-OpenRosa-Version', '1.0');
        }

        await request.expect(401);
      }));
    });
  });

});
