#!/bin/bash -eu
set -o pipefail

serverUrl="http://localhost:8383"
userEmail="x@example.com"
userPassword="secret1234"

log() {
  echo "[test/e2e/s3/ci] $*"
}

fail_job() {
  log 'Job failed.'
  exit 1
}

make base

echo "$userPassword" | node ./lib/bin/cli.js user-create  -u "$userEmail"
node ./lib/bin/cli.js user-promote -u "$userEmail"

NODE_CONFIG_ENV=s3-dev node lib/bin/s3-create-bucket.js
NODE_CONFIG_ENV=s3-dev make run >backend.log 2>&1 &

log 'Waiting for backend to start...'
timeout 30 bash -c "while ! curl -s -o /dev/null $serverUrl; do sleep 1; done"
log 'Backend started!'

node test/e2e/s3/index.js -s "$serverUrl" -P "$userPassword"

if ! curl -s -o /dev/null "$serverUrl"; then
  log 'Backend died.'
  fail_job
fi

log "Test completed OK."
