name: OIDC integration tests

on:
  push:
  pull_request:

jobs:
  oidc-integration-test:
    timeout-minutes: 6
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci
    - run: FAKE_OIDC_ROOT_URL=http://localhost:9898 make fake-oidc-server-ci > fake-oidc-server.log &
    - run: make run-docker-postgres
    - run: make test-oidc-integration
    - name: Fake OIDC Server Logs
      if: always()
      run: "! [[ -f ./fake-oidc-server.log ]] || cat ./fake-oidc-server.log"
