name: OIDC e2e tests

on:
  push:
  pull_request:

env:
  DEBUG: pw:api
  ODK_PLAYWRIGHT_BROWSERS: chromium,firefox,webkit

jobs:
  oidc-e2e-test:
    timeout-minutes: 6
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-latest
    steps:

    # This one weird trick speeds up every build!
    # see: https://github.com/getodk/central-backend/pull/1642
    # see: https://github.com/actions/runner/issues/4030
    - run: sudo apt-get remove --purge man-db

    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci
    - run: make run-docker-postgres
    - run: sudo apt-get install wait-for-it
    - run: ./test/e2e/oidc/run-tests.sh
    - name: Archive Playwright Test Report
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: Playwright Test Report
        path: test/e2e/oidc/playwright-tests/results/html-report/
