name: S3 E2E Tests

on:
  push:
  pull_request:

jobs:
  s3-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        x: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        y: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        postgres-version:
          - "14.23"
          - "18"
    steps:
    - uses: actions/checkout@v6
    - run: make fake-s3-server-persistent
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci --no-audit
    - run: make run-docker-postgres
      env:
        PG_VERSION: ${{ matrix.postgres-version }}
