name: S3 integration tests

on: push

jobs:
  s3-integration-test:
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-latest
    services:
      # see: https://docs.github.com/en/enterprise-server@3.5/actions/using-containerized-services/creating-postgresql-service-containers
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_PASSWORD: odktest
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        # see: https://github.com/minio/minio/discussions/16099
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: odk-central-dev
          MINIO_ROOT_PASSWORD: topSecret123
        options: >-
          --health-cmd "curl -s http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: node lib/bin/create-docker-databases.js
    - run: make test-s3-integration
