name: Soak Test

on:
  push:
    branches: master

jobs:
  soak-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
          - "14.23"
          - "18"
    steps:
    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci
    - run: make run-docker-postgres
      env:
        PG_VERSION: ${{ matrix.postgres-version }}
    - run: ./test/e2e/soak/ci/prepare-postgres.sh
    - name: Soak Test
      timeout-minutes: 10
      run: ./test/e2e/soak/ci/run-tests.sh
    - name: Backend Logs
      if: always()
      run: "! [[ -f ./backend.log ]] || cat ./backend.log"
