name: Full Standard Test Suite

on: push

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
  standard-tests:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    timeout-minutes: 20
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-latest
    services:
      # see: https://docs.github.com/en/enterprise-server@3.5/actions/using-containerized-services/creating-postgresql-service-containers
      postgres:
        image: postgres:14.10
        env:
          POSTGRES_PASSWORD: odktest
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'npm'
    - run: npm ci
    - run: node lib/bin/create-docker-databases.js
    - run: make test
