name: Full Standard Test Suite

on:
  push:
  pull_request:

jobs:
  standard-tests:
    timeout-minutes: 20
    # TODO should we use the same container as circle & central?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set node version
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: make check-for-large-files
    - run: npm ci
    - run: make api-docs-lint

    - run: |
        docker run -d \
          --name postgres \
          --publish 5432:5432 \
          --env POSTGRES_PASSWORD=odktest \
          postgres:14.20-alpine \
            --shared_preload_libraries=pg_stat_statements
    - run: docker exec postgres pg_isready -U postgres --timeout=30
    - run: node lib/bin/create-docker-databases.js
    - run: make test
